namespace LaFabriqueDuPereNoel
{
    public static class DonneesSimulation
    {
public static readonly string[] prenoms = {
    "Alice", "Bob", "Charlie", "Diana", "Emma", "Frank", "Grace", "Hugo", "Iris", "Jack", "Kate", "Leo", "Marie", "Nathan", "Olivia", "Paul",
    "Amélie", "Bastien", "Camille", "David", "Elise", "Félix", "Gabrielle", "Hector", "Inès", "Jules", "Léna", "Maxime", "Noémie", "Oscar", "Pierre", "Quentin",
    "Romain", "Sophie", "Théo", "Ulysse", "Valentine", "William", "Xavier", "Yasmine", "Zoé",
    "Adam", "Benjamin", "Chloé", "Damien", "Émilie", "Florian", "Gaspard", "Honorine", "Isabelle", "Jean", "Laura", "Luc", "Manon", "Nicolas", "Océane", "Pauline",
    "Quincy", "Raphaël", "Sarah", "Timothée", "Ursula", "Victor", "Wendy", "Xena", "Yann", "Zara",
    "Aaron", "Bella", "Cédric", "Delphine", "Élodie", "Fabien", "Gaëlle", "Henri", "Ibrahim", "Jade", "Loris", "Maëlle", "Nolan", "Olivier", "Philippe", "Rita",
    "Samuel", "Tatiana", "Ugo", "Violette", "Warren", "Ximena", "Yves", "Zélie",
    "Alexis", "Bruno", "Cassandra", "Dylan", "Éric", "Fanny", "Géraldine", "Hugo", "Ismaël", "Jasmine", "Kevin", "Lila", "Matthieu", "Nina", "Omar", "Patricia",
    "Quentin", "Rebecca", "Stéphane", "Thalia", "Umut", "Valentin", "William", "Xander", "Yara", "Zachary",
    "Amber", "Blake", "Caitlin", "Derek", "Evelyn", "Felix", "Gwen", "Harry", "Ivy", "Jason", "Kara", "Liam", "Maya", "Noah", "Olga", "Peter",
    "Quinn", "Rachel", "Sean", "Tara", "Uriel", "Vera", "Wesley", "Xavier", "Yvonne", "Zane",
    "Aria", "Beck", "Clara", "Dean", "Ella", "Finn", "Gia", "Heidi", "Ian", "Jade", "Kai", "Luna", "Miles", "Nora", "Owen", "Paige",
    "Quincy", "Rose", "Seth", "Tina", "Uri", "Vince", "Willow", "Xena", "Yosef", "Zia",
    "Aiden", "Bella", "Carlos", "Diana", "Ethan", "Fatima", "Gabriel", "Hana", "Ismail", "Jin", "Kamil", "Lina", "Mia", "Noor", "Omar", "Priya",
    "Ravi", "Sara", "Tariq", "Uma", "Victor", "Wang", "Ximena", "Yusuf", "Zain",
    "Akira", "Bianca", "Cheng", "Diego", "Elena", "Farah", "Giovanni", "Hassan", "Imani", "Jorge", "Katarina", "Leila", "Miguel", "Nadia", "Oleg", "Pavel",
    "Qi", "Rania", "Santiago", "Tatiana", "Umar", "Valeria", "Wei", "Xia", "Yara", "Zara",
    "Anya", "Bruno", "Celia", "Dmitri", "Elif", "Fahim", "Grace", "Hiro", "Idris", "Jamal", "Kaya", "Luca", "Marina", "Nikolai", "Oksana", "Pedro",
    "Qasim", "Rosa", "Stefan", "Tomas", "Usha", "Viktor", "Wafa", "Xander", "Yanis", "Zofia",
    "Alina", "Bartek", "Celeste", "Dario", "Emilia", "Farid", "Goran", "Huda", "Isabella", "Javier", "Karim", "Lara", "Mateo", "Nina", "Orlando", "Patryk",
    "Qiang", "Rita", "Selim", "Talia", "Uri", "Vera", "Wojciech", "Xenia", "Youssef", "Zlatan"
};

        public static readonly string[] adresses ={
    // Europe - France
    "15 rue de la République, Poitiers, France, Europe",
    "32 avenue Victor Hugo, Paris, France, Europe",
    "7 boulevard Saint-Michel, Lyon, France, Europe",
    "12 rue du Faubourg Saint-Antoine, Marseille, France, Europe",
    "5 place Charles de Gaulle, Lille, France, Europe",
    "10 avenue des Champs-Élysées, Paris, France, Europe",
    "27 rue de la Paix, Nice, France, Europe",
    "4 rue des Lilas, Bordeaux, France, Europe",
    "8 avenue de la Gare, Strasbourg, France, Europe",
    "9 place de l’Opéra, Nantes, France, Europe",
    "18 rue Saint-Denis, Rennes, France, Europe",
    "22 avenue Jean Jaurès, Montpellier, France, Europe",
    "50 rue Nationale, Grenoble, France, Europe",
    "33 boulevard Haussmann, Paris, France, Europe",
    "11 rue du Pont, Toulouse, France, Europe",
    "9 rue des Martyrs, Marseille, France, Europe",
    "24 avenue Foch, Nice, France, Europe",
    "5 rue du Château, Dijon, France, Europe",
    "28 rue de la Liberté, Clermont-Ferrand, France, Europe",
    "13 boulevard Voltaire, Lyon, France, Europe",

    // Europe - Royaume-Uni
    "101 Baker Street, Londres, Royaume-Uni, Europe",
    "22 King’s Road, Londres, Royaume-Uni, Europe",
    "15 Queen Street, Édimbourg, Royaume-Uni, Europe",
    "44 High Street, Manchester, Royaume-Uni, Europe",
    "8 Abbey Road, Liverpool, Royaume-Uni, Europe",
    "29 Downing Street, Londres, Royaume-Uni, Europe",
    "50 Oxford Street, Londres, Royaume-Uni, Europe",
    "37 Princes Street, Édimbourg, Royaume-Uni, Europe",
    "16 Market Street, Glasgow, Royaume-Uni, Europe",
    "5 King Street, Belfast, Royaume-Uni, Europe",
    "88 Camden Road, Londres, Royaume-Uni, Europe",
    "77 Fleet Street, Londres, Royaume-Uni, Europe",
    "39 Church Street, Birmingham, Royaume-Uni, Europe",
    "12 Castle Street, Cardiff, Royaume-Uni, Europe",
    "6 Victoria Road, Bristol, Royaume-Uni, Europe",
    "20 The Crescent, Newcastle, Royaume-Uni, Europe",
    "55 King’s Parade, Cambridge, Royaume-Uni, Europe",
    "14 High Street, Oxford, Royaume-Uni, Europe",
    "9 St. Mary’s Lane, Southampton, Royaume-Uni, Europe",
    "42 Queen Street, Glasgow, Royaume-Uni, Europe",

    // Europe - Allemagne
    "17 Unter den Linden, Berlin, Allemagne, Europe",
    "90 Alexanderplatz, Berlin, Allemagne, Europe",
    "8 Königsallee, Düsseldorf, Allemagne, Europe",
    "13 Marienplatz, Munich, Allemagne, Europe",
    "22 Zeil, Francfort, Allemagne, Europe",
    "55 Karl-Marx-Straße, Leipzig, Allemagne, Europe",
    "9 Berliner Strasse, Hambourg, Allemagne, Europe",
    "40 Schlossplatz, Stuttgart, Allemagne, Europe",
    "18 Breite Straße, Dresde, Allemagne, Europe",
    "31 Markt, Cologne, Allemagne, Europe",
    "25 Friedrichstraße, Berlin, Allemagne, Europe",
    "44 Maximilianstraße, Munich, Allemagne, Europe",
    "11 Hohenzollernring, Cologne, Allemagne, Europe",
    "37 Kurfürstendamm, Berlin, Allemagne, Europe",
    "50 Mönckebergstraße, Hambourg, Allemagne, Europe",
    "28 Königstraße, Stuttgart, Allemagne, Europe",
    "14 Rosenstraße, Bremen, Allemagne, Europe",
    "6 Große Bleichen, Hambourg, Allemagne, Europe",
    "23 Luisenstraße, Düsseldorf, Allemagne, Europe",
    "12 Schloßstraße, Berlin, Allemagne, Europe",

    // Europe - Italie
    "28 Piazza del Duomo, Milan, Italie, Europe",
    "19 Via Roma, Rome, Italie, Europe",
    "14 Via Garibaldi, Naples, Italie, Europe",
    "5 Via Toledo, Naples, Italie, Europe",
    "12 Via Dante, Milan, Italie, Europe",
    "7 Via del Corso, Rome, Italie, Europe",
    "30 Via dei Condotti, Rome, Italie, Europe",
    "10 Via Sparano, Bari, Italie, Europe",
    "8 Via Mazzini, Verona, Italie, Europe",
    "22 Via Etnea, Catane, Italie, Europe",
    "15 Via Nazionale, Florence, Italie, Europe",
    "13 Via Larga, Florence, Italie, Europe",
    "11 Via XX Settembre, Genoa, Italie, Europe",
    "9 Via Garibaldi, Genoa, Italie, Europe",
    "4 Via Manzoni, Milan, Italie, Europe",

    // Europe - Espagne
    "14 La Rambla, Barcelone, Espagne, Europe",
    "7 Calle Mayor, Madrid, Espagne, Europe",
    "12 Gran Vía, Madrid, Espagne, Europe",
    "8 Passeig de Gràcia, Barcelone, Espagne, Europe",
    "19 Calle Alcalá, Madrid, Espagne, Europe",
    "22 Plaza Mayor, Madrid, Espagne, Europe",
    "5 Calle Larios, Malaga, Espagne, Europe",
    "17 Calle del Arenal, Madrid, Espagne, Europe",
    "10 Rambla Nova, Tarragone, Espagne, Europe",
    "6 Calle de Preciados, Madrid, Espagne, Europe",

    // Europe - autres pays
    "8 Vaci utca, Budapest, Hongrie, Europe",
    "33 Grote Markt, Bruxelles, Belgique, Europe",
    "12 Strada Lipscani, Bucarest, Roumanie, Europe",
    "4 Rådhuspladsen, Copenhague, Danemark, Europe",
    "21 Esplanadi, Helsinki, Finlande, Europe",
    "6 Place de la Constitution, Varsovie, Pologne, Europe",
    "10 Vieille ville, Prague, République tchèque, Europe",
    "11 Avenida Central, Lisbonne, Portugal, Europe",
    "33 Rue de la Paix, Bruxelles, Belgique, Europe",
    "25 Rue Sainte-Catherine, Bordeaux, France, Europe",
    "12 Piazza Navona, Rome, Italie, Europe",
    "17 Old Town, Prague, République tchèque, Europe",
    "5 Place Rouge, Moscou, Russie, Europe",
    "40 Gran Via, Madrid, Espagne, Europe",
    "9 Oxford Circus, Londres, Royaume-Uni, Europe",
    "55 Rue Saint-Honoré, Paris, France, Europe",
    "62 Grafton Street, Dublin, Irlande, Europe",

    // Amérique - États-Unis
    "120 Broadway, New York, États-Unis, Amerique",
    "35 Wall Street, New York, États-Unis, Amerique",
    "12 Fifth Avenue, New York, États-Unis, Amerique",
    "200 Sunset Blvd, Los Angeles, États-Unis, Amerique",
    "42 Michigan Avenue, Chicago, États-Unis, Amerique",
    "9 Market Street, San Francisco, États-Unis, Amerique",
    "100 Main Street, Seattle, États-Unis, Amerique",
    "80 Elm Street, Boston, États-Unis, Amerique",
    "55 Peachtree Street, Atlanta, États-Unis, Amerique",
    "44 King Street, Miami, États-Unis, Amerique",
    "71 Canal Street, New Orleans, États-Unis, Amerique",
    "18 Congress Avenue, Austin, États-Unis, Amerique",
    "22 Park Avenue, New York, États-Unis, Amerique",
    "37 Madison Avenue, New York, États-Unis, Amerique",
    "5 Pine Street, San Francisco, États-Unis, Amerique",
    "33 Broadway, New York, États-Unis, Amerique",
    "12 H Street, Washington, États-Unis, Amerique",
    "20 Market Street, Philadelphia, États-Unis, Amerique",
    "15 Elm Street, Dallas, États-Unis, Amerique",
    "30 Walnut Street, Denver, États-Unis, Amerique",

    // Amérique - Canada
    "320 Queen Street, Toronto, Canada, Amerique",
    "45 King Street, Toronto, Canada, Amerique",
    "123 Granville Street, Vancouver, Canada, Amerique",
    "78 Sainte-Catherine Street, Montréal, Canada, Amerique",
    "15 Robson Street, Vancouver, Canada, Amerique",
    "5 Rue Sherbrooke, Montréal, Canada, Amerique",
    "90 Prince Arthur Avenue, Ottawa, Canada, Amerique",
    "33 Bank Street, Ottawa, Canada, Amerique",
    "19 Portage Avenue, Winnipeg, Canada, Amerique",
    "25 Grafton Street, Halifax, Canada, Amerique",
    "42 Main Street, Quebec City, Canada, Amerique",
    "8 King Street, Calgary, Canada, Amerique",
    "14 Broadway Avenue, Edmonton, Canada, Amerique",
    "60 Douglas Street, Victoria, Canada, Amerique",
    "22 Cambie Street, Vancouver, Canada, Amerique",

    // Amérique - Amérique Latine
    "220 Avenida Atlântica, Rio de Janeiro, Brésil, Amerique",
    "80 Rua das Flores, São Paulo, Brésil, Amerique",
    "10 Avenida Revolución, Mexico, Mexique, Amerique",
    "12 Calle 13, Bogotá, Colombie, Amerique",
    "40 Avenida Paulista, São Paulo, Brésil, Amerique",
    "33 Calle 72, Medellín, Colombie, Amerique",
    "17 Calle 7, Buenos Aires, Argentine, Amerique",
    "21 Avenida Bolívar, Caracas, Venezuela, Amerique",
    "9 Avenida 9 de Julio, Buenos Aires, Argentine, Amerique",
    "50 Avenida Amazonas, Quito, Équateur, Amerique",
    "8 Rua Augusta, Rio de Janeiro, Brésil, Amerique",
    "13 Calle del Prado, La Paz, Bolivie, Amerique",
    "27 Avenida Bolívar, Lima, Pérou, Amerique",
    "5 Calle Uruguay, Montevideo, Uruguay, Amerique",
    "11 Avenida Reforma, Guatemala, Guatemala, Amerique",

    // Afrique
    "10 Nile Street, Le Caire, Égypte, Afrique",
    "27 Mandela Road, Johannesburg, Afrique du Sud, Afrique",
    "5 Independence Avenue, Nairobi, Kenya, Afrique",
    "3 Rue des Fleurs, Casablanca, Maroc, Afrique",
    "44 Independence Street, Dakar, Sénégal, Afrique",
    "22 Kwame Nkrumah Avenue, Accra, Ghana, Afrique",
    "18 Julius Nyerere Way, Dar es Salaam, Tanzanie, Afrique",
    "55 Ahmed Sékou Touré Boulevard, Conakry, Guinée, Afrique",
    "60 Addis Ababa Road, Addis-Abeba, Éthiopie, Afrique",
    "9 Patrice Lumumba Street, Kinshasa, RDC, Afrique",
    "11 Commercial Street, Lagos, Nigeria, Afrique",
    "16 Victoria Road, Cape Town, Afrique du Sud, Afrique",
    "8 Liberation Avenue, Harare, Zimbabwe, Afrique",
    "24 Freedom Street, Tunis, Tunisie, Afrique",
    "30 Independence Boulevard, Algiers, Algérie, Afrique",

    // Océanie
    "15 Oxford Street, Sydney, Australie, Oceanie",
    "5 George Street, Sydney, Australie, Oceanie",
    "32 Queen Street, Auckland, Nouvelle-Zélande, Oceanie",
    "8 Collins Street, Melbourne, Australie, Oceanie",
    "10 Victoria Street, Wellington, Nouvelle-Zélande, Oceanie",
    "12 King Street, Brisbane, Australie, Oceanie",
    "6 Adelaide Road, Canberra, Australie, Oceanie",
    "22 Hickson Road, Sydney, Australie, Oceanie",
    "40 Queen Street, Dunedin, Nouvelle-Zélande, Oceanie",
    "18 Courtenay Place, Wellington, Nouvelle-Zélande, Oceanie",
    "11 Devonport Road, Auckland, Nouvelle-Zélande, Oceanie",
    "7 Elizabeth Street, Hobart, Australie, Oceanie",
    "19 Victoria Avenue, Christchurch, Nouvelle-Zélande, Oceanie",
    "25 Wynyard Street, Auckland, Nouvelle-Zélande, Oceanie",
    "13 Wharf Street, Cairns, Australie, Oceanie",

    // Asie - Japon, Chine, Inde, autres
    "100 Shibuya Crossing, Tokyo, Japon, Asie",
    "12-3 Ginza, Tokyo, Japon, Asie",
    "45-6 Shinjuku, Tokyo, Japon, Asie",
    "7-15-8 Roppongi, Tokyo, Japon, Asie",
    "88 Nanjing Road, Shanghai, Chine, Asie",
    "16 Wangfujing, Pékin, Chine, Asie",
    "50 MG Road, Bangalore, Inde, Asie",
    "21 Brigade Road, Bangalore, Inde, Asie",
    "5 Orchard Road, Singapour, Singapour, Asie",
    "23 Marina Bay, Singapour, Singapour, Asie",
    "14 Jalan Bukit Bintang, Kuala Lumpur, Malaisie, Asie",
    "28 Sukhumvit Road, Bangkok, Thaïlande, Asie",
    "18 Phạm Ngũ Lão, Ho Chi Minh-Ville, Vietnam, Asie",
    "7 Jalan Petaling, Kuala Lumpur, Malaisie, Asie",
    "35 M G Road, Mumbai, Inde, Asie",
    "45 Dongzhimen, Pékin, Chine, Asie",
    "60 Tverskaya Street, Moscou, Russie, Europe",
    "33 Nevsky Prospekt, Saint-Pétersbourg, Russie, Europe",

    // Russie (Europe et Asie)
    "101 Arbat Street, Moscou, Russie, Europe",
    "10 Nevsky Prospect, Saint-Pétersbourg, Russie, Europe",
    "5 Tverskaya Street, Moscou, Russie, Europe",
    "15 Leninsky Prospect, Moscou, Russie, Europe",
    "20 Arbat Street, Moscou, Russie, Europe",
    "7 Prospekt Mira, Moscou, Russie, Europe",

    // Plus d’adresses variées supplémentaires
    "44 Rue de la Paix, Paris, France, Europe",
    "36 Rue Lafayette, Paris, France, Europe",
    "55 Rue des Martyrs, Paris, France, Europe",
    "12 Place Bellecour, Lyon, France, Europe",
    "27 Place du Capitole, Toulouse, France, Europe",
    "15 Rue du Faubourg Saint-Honoré, Paris, France, Europe",
    "31 Avenue Montaigne, Paris, France, Europe",
    "24 Place Vendôme, Paris, France, Europe",
    "13 Rue des Rosiers, Paris, France, Europe",
    "18 Quai de la Tournelle, Paris, France, Europe",

    // Moyen-Orient - Israël
    "12 Rothschild Boulevard, Tel Aviv, Israël, Asie",
    "45 King George Street, Jérusalem, Israël, Asie",
    "9 Allenby Street, Tel Aviv, Israël, Asie",
    "27 Jaffa Road, Jérusalem, Israël, Asie",
    "15 Herzl Street, Haïfa, Israël, Asie",
    "7 Ibn Gabirol Street, Tel Aviv, Israël, Asie",
    "33 Ben Yehuda Street, Jérusalem, Israël, Asie",
    "10 HaTayasim Street, Rishon LeZion, Israël, Asie",
    "5 Dizengoff Street, Tel Aviv, Israël, Asie",
    "21 Haatzmaut Street, Beersheba, Israël, Asie",

    // Moyen-Orient - Liban
    "12 Hamra Street, Beyrouth, Liban, Asie",
    "45 Charles Helou Avenue, Beyrouth, Liban, Asie",
    "9 Verdun Street, Beyrouth, Liban, Asie",
    "27 Sassine Street, Jounieh, Liban, Asie",
    "15 Mar Mikhael Street, Beyrouth, Liban, Asie",
    "7 Zalka Highway, Zalka, Liban, Asie",
    "33 Jal El Dib Highway, Jal El Dib, Liban, Asie",
    "10 Hamra Street, Beyrouth, Liban, Asie",
    "5 Sanayeh Street, Beyrouth, Liban, Asie",
    "21 Corniche El Mazraa, Beyrouth, Liban, Asie",

    // Moyen-Orient - Jordanie
    "12 Rainbow Street, Amman, Jordanie, Asie",
    "45 Queen Rania Street, Amman, Jordanie, Asie",
    "9 Abdoun Street, Amman, Jordanie, Asie",
    "27 Al-Madina Al-Monawara Street, Amman, Jordanie, Asie",
    "15 Wasfi Al-Tal Street, Amman, Jordanie, Asie",

    // Moyen-Orient - Koweït
    "15 Fahad Al Salem Street, Koweït, Koweït, Asie",
    "7 Gulf Road, Koweït, Koweït, Asie",
    "33 Al-Murqab Street, Koweït, Koweït, Asie",
    "10 Jamal Abdul Nasser Street, Koweït, Koweït, Asie",

    // Moyen-Orient - Bahreïn
    "22 Exhibition Road, Manama, Bahreïn, Asie",
    "9 Sheikh Isa Bin Salman Highway, Manama, Bahreïn, Asie",
    "5 Al Fateh Highway, Manama, Bahreïn, Asie",

    // Moyen-Orient - Qatar
    "18 Corniche Street, Doha, Qatar, Asie",
    "7 Al Rayyan Road, Doha, Qatar, Asie",
    "33 Al Waab Street, Doha, Qatar, Asie",
    "10 Salwa Road, Doha, Qatar, Asie",

    // Moyen-Orient - Oman
    "12 Sultan Qaboos Street, Mascate, Oman, Asie",
    "45 Al Khuwair Street, Mascate, Oman, Asie",
    "9 Way Al Khalili, Mascate, Oman, Asie",

    // Moyen-Orient - Émirats Arabes Unis
    "15 Sheikh Zayed Road, Dubaï, Émirats Arabes Unis, Asie",
    "7 Al Maktoum Street, Dubaï, Émirats Arabes Unis, Asie",
    "33 Khalifa Street, Abu Dhabi, Émirats Arabes Unis, Asie",
    "10 Al Ain Road, Abu Dhabi, Émirats Arabes Unis, Asie",

    // Moyen-Orient - Turquie (partie Asie)
    "12 Bağdat Caddesi, Istanbul, Turquie, Asie",
    "45 Atatürk Street, Ankara, Turquie, Asie",
    "9 Cumhuriyet Avenue, Izmir, Turquie, Asie"
};
    }
}   